### ISSUE TITLE
Question: Using autometrics in a database (postgresql)?

### ISSUE THREAD

**Issue by aiswaryapajit** [autometrics-dev/autometrics-py#68]
can we use autometrics to be run at database side(postgresql) or is there any way to use api of autometrics

**Comment by brettimus** [comment]
hey! so discussed this with @actualwitch this morning. 

if you want to track metrics of database queries, you would have to wrap your application code that calls the database. of course, this doesn't give you metrics on specific subqueries, and would include the latency of sending the request to the database server, however! it would give you metrics there.

to make it concrete, this is what you'd be trying to do, application-side:

```py
@auotmetrics
def list_all_users():
  return db.query("select * from users")
```

**Comment by brettimus** [comment]
a little bit off topic, but @actualwitch pointed out that lots of python APIs will use context instead of functions for this kind of (db) operation. she proposed supporting instrumentation via context manager [here](https://github.com/autometrics-dev/autometrics-py/issues/70)

i'm going to close this issue as answered!
